### PR TITLE
Updating the french translation and correcting some things

### PR DESCRIPTION
**Pull request by NonoLePoulet**
Added translation and corrected some sentences :)

### CODE REVIEW

**Comment by VercroXft** [comment]
i review the translate into more than 700 word

**Comment by NonoLePoulet** [comment]
Ok, thanks :)

**Comment by mty22** [comment]
I've received feedback from Chwoubaka and Atzelord, some concerns were raised in regards to the proposed changes.

@NonoLePoulet can you please reach out to them directly? Their Discord contact information is in the README file under Contributors:

https://github.com/mty22/krunker.io-translations/blob/main/README.md

**Comment by NonoLePoulet** [comment]
Ok, I'll reach out to them :)

**Comment by mty22** [comment]
Had a chat with @Chwoubaka  who since spoke with @NonoLePoulet - we will close this PR and re-submit a new one with.,

**Comment by NonoLePoulet** [comment]
With what ?

**Pull request closed without merging**
