### PR TITLE
Updated fr.js based on en.js v4.0.9

### PR DESCRIPTION
**Pull request by enygmate**

### CODE REVIEW

**Comment by mty22** [comment]
Legend, thank you! Pending review from native speakers.

**Comment by mty22** [comment]
@enygmate did you have anyone to review by any chance?

**Comment by enygmate** [comment]
> @enygmate did you have anyone to review by any chance?

I will ask a few people

**Review by R3dlessX — APPROVED** [review]
Good Job Sir

**Comment by enygmate** [comment]
missclick 😑😐

**Comment by mty22** [comment]
@R3dlessX can you please let me know your Krunker IGN?

**Comment by mty22** [comment]
KR sent, also waiting on Redless.

**Comment by enygmate** [comment]
> KR sent, also waiting on Redless.

I believe this is his account: [R3dlessX](https://krunker.io/social.html?p=profile&q=R3dlessX)
He isn't an active krunker player though

**Pull request merged**
