### PR TITLE
Update kr.js

### PR DESCRIPTION
**Pull request by tr0922**

### CODE REVIEW

**Comment by tr0922** [comment]
Little edits on the kr.js.

**Review by apinklover — DISMISSED** [review]
Was wanting to make those changes too, nice work! Approved.

**Comment by tr0922** [comment]
@apinklover Thank you <333

**Comment by YuniQ152** [comment]
708번째 줄의 텍스트는 크런커 허브에서 텍스트 끝에 자동으로 "KR"이 붙게됩니다. "선물할 금액"으로 바꾸면 허브에서 실제로는 "선물할 금액 KR"로 보이게 되어서 그냥 냅두는게 더 나아보여요.

673번째 줄은 허브에서 계정 생성일뿐만 아니라 팔로잉/팔로워 목록에서도 뜨는 텍스트라 "회원가입 날짜"로 변경하면 어색해보입니다. 근데 기존의 "첫 등록일"도 의미가 딱 맞아떨어지지는 않아서 애매하네요.

**Comment by apinklover** [comment]
@YuniQ152 그렇네요. 님이 제안하신 쪽으로 편집합시다 

@tr0922

**Comment by mty22** [comment]
let me know when good to merge

**Comment by tr0922** [comment]
@YuniQ152 @tr0922 YuniQ's absolutely right. Kinda didn't check how the real text would show when it's in real Socials.
I'm in my dormitory atm, so kind of missed that, sorry.
I'm gonna make changes. Check plz!

**Review by YuniQ152 — APPROVED** [review]
Good :]

**Comment by goonmandu** [comment]
@tr0922 How about instead of 시작일, we use 계정 생성? I'll wait for your response, then I'll give the green light to merge.

**Comment by YuniQ152** [comment]
저 텍스트가 Krunker Hub의 팔로워/팔로잉 텍스트에서도 뜨는거라서 '계정 생성'으로 의미를 좁혀버리면 어색할 수 있습니다. image

**Comment by mty22** [comment]
just a note, will have a new `en.js` soon.. so I'd like to finish this PR up soon :)

**Comment by goonmandu** [comment]
I say we push this request without the considerations that @YuniQ152 brought up (the account creation date label), leave it as it was for the time being and think about it more thoroughly later. I've yet been able to find a suitable Korean translation that would also be compliant with how the game text is coded ("Since" {date}).

**Comment by mty22** [comment]
OK thanks @goonmandu - we can address his comment in the next pull request!

I'll merge this one tomorrow.

**Review by mty22 — APPROVED** [review]

**Comment by mty22** [comment]
kr queued

**Pull request merged**
