### PR TITLE
Updated fr.js based on pull 251

### PR DESCRIPTION
**Pull request by enygmate**

### CODE REVIEW

**Comment by enygmate** [comment]
that was a missclick 😐
image

**Comment by mty22** [comment]
@enygmate do you have anyone who can review?

**Comment by mty22** [comment]
pending review still

**Comment by Sayrix** [comment]
Pog

**Review by MichelBaie — APPROVED** [review]
very good networking traduction. the traduction is very frenchy 🥖

**Review by Sayrix — APPROVED** [review]
Pog

**Comment by mty22** [comment]
Thanks fellas!

**Comment by mty22** [comment]
kr queued

**Pull request merged**
