### PR TITLE
zhtw.js Synced with #138

### PR DESCRIPTION
**Pull request by WpyGG4125**
Revamped previous file and fixed mistakes, also changed some translation inaccuracies.
This is a more generalised Traditional Chinese version, therefore it does not have any biased translations according to regions (tw, hk etc).
Purely self-made file, not based on other translations files (except taking examples from the original simplified chinese version).
If you see any flaws feel free to ping.

**### _All translations are now moved into #138 as for the collaboration_**

### CODE REVIEW

**Comment by WpyGG4125** [comment]
@mty22 @Therealzz @RIFLEJI

**Review by Therealzz — CHANGES_REQUESTED** [review]
I have reviewed the first 100 lines of the localization strings. So far, this one seems a lot better.

Improvement & Suggestions:
```
menu.btn.mods 模組
//外掛程式 is ambiguous with "cheat programs"

generic.name 用戶名
// 使用者名 is not generally used imo

generic.follow 追隨 
generic.unfollow 取消追蹤 
generic.followers 追隨者 
generic.following 追隨中
// for more consistency

player.inactive 閒置過久，遊戲已斷開連接
player.killed 擊殺你的人 
app.play 點擊以開始遊戲
app.spectate 點擊以觀戰此局遊戲
app.play.controller 按任意鍵開始
purchase.error.click 點擊</a> 並重試！ 
timer.end 下一場將在 {0} 秒後開始 
leaderboard.empty 未有任何玩家
popup.checkpoint 重生點己更新！ 
settings.none 未有找到設定

settings.local.header 本地化 <span id="requiresRestart"><span style="color： #eb5656">*</span> 需重啟遊戲</span>
//本地言系化 is not generally used imo

settings.local.region 預設地區
settings.network.sendRate 高效伺服器 
settings.network.lagComp 延遲補正（Lag Compensation）
settings.network.netRerouting 自動搜尋最佳網路
settings.experimental.shaderRendering 物件渲染優化
settings.dev.header 開發者
settings.dev.forceRegen 永遠強制復活玩家
settings.dev.extraBan 額外封禁資訊
```

**Comment by WpyGG4125** [comment]
> I have reviewed the first 100 lines of the localization strings. So far, this one seems a lot better.
> 
> Improvement & Suggestions:
> menu.btn.mods 模組
> //外掛程式 is ambiguous with "cheat programs"
> 
> generic.name 用戶名
> // 使用者名 is not generally used imo
> 
> generic.follow 追隨
> generic.unfollow 取消追蹤
> generic.followers 追隨者
> generic.following 追隨中
> // for more consistency
> 
> player.inactive 閒置過久，遊戲已斷開連接
> player.killed 擊殺你的人
> app.play 點擊以開始遊戲
> app.spectate 點擊以觀戰此局遊戲
> app.play.controller 按任意鍵開始
> purchase.error.click 點擊 並重試！
> timer.end 下一場將在 {0} 秒後開始
> leaderboard.empty 未有任何玩家
> popup.checkpoint 重生點己更新！
> settings.none 未有找到設定
> 
> settings.local.header 本地化 * 需重啟遊戲
> //本地言系化 is not generally used imo
> 
> settings.local.region 預設地區
> settings.network.sendRate 高效伺服器
> settings.network.lagComp 延遲補正（Lag Compensation）
> settings.network.netRerouting 自動搜尋最佳網路
> settings.experimental.shaderRendering 物件渲染優化
> settings.dev.header 開發者
> settings.dev.forceRegen 永遠強制復活玩家
> settings.dev.extraBan 額外封禁資訊

cough cough cough Idk how I didnt see the mods one
I've used 插件 for the rest, idk y i left the first one unseen

I'll use 追隨者 for all followers related concepts
wait why do i have so many things wtf

**Comment by WpyGG4125** [comment]
kekw I really don't know how I let so many things slip
Reviewed again, this time it should be fine................

**Review by Therealzz — CHANGES_REQUESTED** [review]
I have done reviewing Line 100-200. Caught by other stuffs, I think I will stop here today.

Improvement & Suggestions:
```
settings.chat.messages 顯示玩家訊息
settings.chat.unboxings 顯示開箱訊息
settings.chat.chatOp 聊天視窗透明度 
settings.chat.chatBGOp 聊天視窗背景透明度
settings.chat.chatTimer 訊息顯示時間
settings.chat.chatTextOutline 訊息文字輪廓
// 窗口 -> 視窗

settings.quality.antiAlias 反鋸齒
settings.quality.softShad 柔和陰影

settings.quality.ambientOld 舊版陰影畫風 （僅可用時）

settings.post.bloom 光暈
settings.post.bloomThreshold 光暈閾值
settings.post.bloomStrength 光暈強度
settings.post.bloomRadius 光暈半徑

settings.post.ssao 螢幕空間環境光遮蔽
settings.post.ssaoRadius 螢幕空間環境光遮蔽半徑
// Chose words that are commonly used by other games

settings.interface.hitInd 命中提示
settings.interface.hitColor 命中提示顏色 

settings.interface.showTradeMsg 顯示交易訊息

settings.interface.killf 顯示擊殺訊息
// Optional

settings.interface.kd 顯示擊殺死亡比例
settings.interface.spectators 顯示觀戰人數

settings.interface.hideNames.all 全部顯示
// Consistency

settings.interface.nametagStyle.name 僅限名稱 
settings.interface.nametagStyle.nameLvl 名稱及等級
settings.interface.nametagStyle.all 全部顯示
// Consistency
```

**Review by Therealzz — CHANGES_REQUESTED** [review]
Please..
```
stats.headshots 爆頭擊殺
stats.wallbangs 穿牆擊殺
```

**Comment by Therealzz** [comment]
is this still pending for review?

**Comment by mty22** [comment]
I've asked both @WpyGG4125  and @Awesome-Boy-001 to work together on this.

**Comment by mty22** [comment]
Bonus KR available for a native speaker to review this.

**Comment by mty22** [comment]
if you're syncing with https://github.com/mty22/krunker.io-translations/pull/138 -- then we'll close this PR and work from the other!~

**Pull request closed without merging**
