### PR TITLE
New zhtr.js

### PR DESCRIPTION
**Pull request by Awesome-Boy-001**
### Full translation to Traditional Chinese language. Bug-free and no white space included.

_Note: Please view the latest commit since made 2nd changes._

**Teamed with:** inv#6091, searinsin#1061.

**Contact:**
**Discord ID:** Awesome_Boy#7555

### CODE REVIEW

**Comment by Awesome-Boy-001** [comment]
I know there's a duplicate file but I would like to see the differences between WpyGG's and our team's.

**Comment by mty22** [comment]
Whilst this has not been approved, it'll likely go ahead. Need a native speaker to review.

**Comment by WpyGG4125** [comment]
......

**Review by Therealzz — COMMENTED** [review]
There are some Simplified Chinese characters inside the translation.
Some wordings in the translation don't match the convention of zh-tw and zh-hk localization.

Discord ID: zzdev#6948
I could help reviewing the translation quality and provide suggestions as a native speaker of zh-hk

**Comment by WpyGG4125** [comment]
@Therealzz could you take a look at #114 please?

**Comment by Therealzz** [comment]
> @Therealzz could you take a look at #114 please?

Is that the latest version of the translation file?

**Comment by WpyGG4125** [comment]
There are some issues with the last lines, similar grammar issues with the simplified chinese translation

**Comment by Awesome-Boy-001** [comment]
@WpyGG4125 Yes I'll fix it

**Comment by Awesome-Boy-001** [comment]
Updated some fixes, grammar issues, and wordings. Please see the latest commit to view the changes.

**Comment by mty22** [comment]
I've asked both @WpyGG4125  and @Awesome-Boy-001 to work together on this.

**Comment by mty22** [comment]
Bonus KR available for a native speaker to review this.

**Comment by Awesome-Boy-001** [comment]
Final version of Traditional Chinese translation. WpyGG helped with line 0-400, I worked from line 400-end.
If there's any questions or errors in the text, feel free to let me or Wpy know. 

**Teamed with:** WpyGG
**Team (Old):** Searinsin, Inv

**Contact:**
**Discord ID:** Awesome_Boy#7555

**Review by Therealzz — CHANGES_REQUESTED** [review]
I have reviewed the entire file. The overall localization quality is acceptable but not perfect imo.

Here's some changes on the file that has to be made fixing the grammar and consistency:

app.play.mobile 輕觸以開始遊戲
app.spectate.mobile 輕觸以觀察賽場

settings.post.header 後期處理

windows.servers.priority 優先顯示預設區域

windows.controls.interact 互動
windows.controls.interactSec 次要互動
windows.controls.confirm 確認互動

windows.clans.members ({0}) 個公會成員

windows.clans.page [{0}] 公會頁面
windows.clans.create 創建公會
windows.clans.name 公會名稱
windows.clans.view 瀏覽公會
windows.clans.join 加入公會
windows.clans.login 創建並加入公會!

windows.reticle.unlocked 於 {0} 等級解鎖

windows.ranked.level 您至少需要 <span color="black"> {0} 級</span> 以進行排位賽! 當前您的等級是 <span color="black"> {1} 級 </span>.

windows.ranked.mode.r1v1 單排
windows.ranked.mode.r2v2 雙排
windows.ranked.mode.r4v4 四排

custom.map.upload.limit 失敗. 遊戲數據限制總共五十萬個字元.

server.config.tickRI 高應答率

server.config.airStrf 空中轉向

social.market.posting 發佈中...

account.banned.hack 此帳號因作弊已被禁用.

windows.host.default.settings 啟用默認設置允許玩家儲存他們的進度及高分

windows.host.rewards 啟用 KR 獎勵將會強制此伺服器使用預設設定並允許玩家從此地圖贏得 KR :

windows.store.wheels.sub 試試您的運氣，轉動獎輪來獲得贏取新皮膚的機會!


windows.clan.leave 您確定您想離開您的公會!?
windows.clan.delete 您確定您想刪除您的公會!?
windows.clan.kick 您確定您想從您的公會踢出 {0} !?
windows.playerlist.ban 您確定您想要從此遊戲封禁並踢出 {0} ?

**Comment by Awesome-Boy-001** [comment]
> I have reviewed the entire file. The overall localization quality is acceptable but not perfect imo.
> 
> Here's some changes on the file that has to be made fixing the grammar and consistency:
> 
> app.play.mobile 輕觸以開始遊戲
> app.spectate.mobile 輕觸以觀察賽場
> 
> settings.post.header 後期處理
> 
> windows.servers.priority 優先顯示預設區域
> 
> windows.controls.interact 互動
> windows.controls.interactSec 次要互動
> windows.controls.confirm 確認互動
> 
> windows.clans.members ({0}) 個公會成員
> 
> windows.clans.page [{0}] 公會頁面
> windows.clans.create 創建公會
> windows.clans.name 公會名稱
> windows.clans.view 瀏覽公會
> windows.clans.join 加入公會
> windows.clans.login 創建並加入公會!
> 
> windows.reticle.unlocked 於 {0} 等級解鎖
> 
> windows.ranked.level 您至少需要 {0} 級 以進行排位賽! 當前您的等級是 {1} 級 .
> 
> windows.ranked.mode.r1v1 單排
> windows.ranked.mode.r2v2 雙排
> windows.ranked.mode.r4v4 四排
> 
> custom.map.upload.limit 失敗. 遊戲數據限制總共五十萬個字元.
> 
> server.config.tickRI 高應答率
> 
> server.config.airStrf 空中轉向
> 
> social.market.posting 發佈中...
> 
> account.banned.hack 此帳號因作弊已被禁用.
> 
> windows.host.default.settings 啟用默認設置允許玩家儲存他們的進度及高分
> 
> windows.host.rewards 啟用 KR 獎勵將會強制此伺服器使用預設設定並允許玩家從此地圖贏得 KR :
> 
> windows.store.wheels.sub 試試您的運氣，轉動獎輪來獲得贏取新皮膚的機會!
> 
> windows.clan.leave 您確定您想離開您的公會!?
> windows.clan.delete 您確定您想刪除您的公會!?
> windows.clan.kick 您確定您想從您的公會踢出 {0} !?
> windows.playerlist.ban 您確定您想要從此遊戲封禁並踢出 {0} ?

I've made the changes to the file and should be looking pretty smooth now. For "windows.ranked.level 您至少需要 {0} 級 以進行排位賽! 當前您的等級是 {1} 級 .", I think we have to include the span in the text.

**Comment by mty22** [comment]
alright so if @WpyGG4125 is syncing against this PR, it make sense just to work in this one.


@Therealzz @WpyGG4125 @Awesome-Boy-001 is there anything left to do? any blockers?

also can you please let me know work percentage breakdowns including reviewers?

**Comment by Awesome-Boy-001** [comment]
**Work Breakdowns Percentage:**

Therealzz (PR Reviewer): 10%
WpyGG (Line 0-400): 40%
Awesome_Boy (Line 400-End, Files Combination): 50%

**Comment by WpyGG4125** [comment]
> **Work Breakdowns Percentage:**
> 
> Therealzz (PR Reviewer): 10%
> WpyGG (Line 0-400): 40%
> Awesome_Boy (Line 400-End, Files Combination): 50%

I'm fine with that 👍

**Comment by mty22** [comment]
Looks good! I'll merge this one in tomorrow then and send KR out !

@Therealzz whats your discord user?

**Comment by mty22** [comment]
@Therealzz can you plz tell me your IGN

**Comment by mty22** [comment]
@Therealzz can you plz tell me your IGN so i can send you KR

**Pull request merged**
