### PR TITLE
Slovenian Translation of Krunker

### PR DESCRIPTION
**Pull request by Basketboss23**
We have been told to submit our Pull-Request in the Slovenian language. We have been working with regard to the in-game context and translated it 100%. If there is an update needed, we can fix it straight away.
Thank you for your approval!

### CODE REVIEW

**Comment by mty22** [comment]
Very nice. Were all the people listed here involved? https://github.com/mty22/krunker.io-translations/issues/57

**Comment by Basketboss23** [comment]
> Very nice. Were all the people listed here involved? #57

Yes, me (`Basketboss23#0723`), `IG5K#7389` and `Kekec#0004`

**Review by DarkWolf03 — APPROVED** [review]
I'm a native Slovenian speaker. I think they did a really good job. I would love to see slovene language to be added in game.

**Review by YourRAGEzzz — APPROVED** [review]
Pog, Slovenian language is getting added to the game. I'm from Slovenia and I think it's perfect. I would use the same words

**Comment by mty22** [comment]
OK, I've added this to `work-in-progress` folder since the language hasn't been approved.

If we approve and add it to the game, I'll reach out to you guys!

**Comment by Basketboss23** [comment]
> OK, I've added this to `work-in-progress` folder since the language hasn't been approved.
> 
> If we approve and add it to the game, I'll reach out to you guys!

Okay great. I have a question. Do you guys have any plans for when non-approved languages will be added? I mean like a timeline?
And thank you for accepting our Pull Request.

**Pull request merged**
