### PR TITLE
french translation update

### PR DESCRIPTION
**Pull request by nerrrrrrrdy**
translated challenge requirements and more stuff

### CODE REVIEW

**Comment by mty22** [comment]
@enygmate are you able to review if/when you get the chance? thank you!

**Comment by enygmate** [comment]
> @enygmate are you able to review if/when you get the chance? thank you!

Yes sorry been a bit busy lately, will do that today!

**Review by enygmate — CHANGES_REQUESTED** [review]
-Line 94: Réseautage is an abuse of language and optimisé is spelled with an s. I would suggest "Optimisation du réseau" instead

-Line 114: ressources is spelled with two s's

-Line 176: Thème is spelled with an è

-Lines 220-221: You forgot to remove the original translation

-Lines 225-226: I would put the axis after Décalage rather than at the end

-Lines 839 & 891: You forgot to remove the original translation

-Line 905: Dérapantes is spelled with an é

-Line 912: échappées-belles is spelled with ée

-Line 913: revenge isn't a french translation, i would use vengeance instead

Other than spelling mistakes and forgotten original translations, I approve the overall translation but this just needs to be fixed firstly

**Comment by nerrrrrrrdy** [comment]
should be fixed now
https://github.com/nerrrrrrrdy/krunker.io-translations/blob/patch-1/fr.js

**Review by enygmate — APPROVED** [review]
Looks good to me

**Comment by mty22** [comment]
@nerrrrrrrdy can you please let me know what your IGN is?

thanks again @enygmate - i'll sort out your badge soon.

**Comment by nerrrrrrrdy** [comment]
nerdyboyobob

**Pull request merged**
