### PR TITLE
Update Spanish translation (v3.8.1)

### PR DESCRIPTION
**Pull request by Sonicglass**
Edited social translation , Added Account, Custom passcode , Funds , Spin and stats Translation. ( Edited or added since number 672 to 724)

### CODE REVIEW

**Comment by Sonicglass** [comment]
I will translate the other part of the code, I love doing this tranlations

**Comment by mty22** [comment]
@Sonicglass perfect - thank you!

Can you please let me know your Krunker IGN and Discord username?

**Comment by mty22** [comment]
@xlNightmare can you review please?

**Review by AleGamer22 — CHANGES_REQUESTED** [review]
Im from Spain i spek and write spanish very well I translated everything that was missing from the code. Discord: AlejandroMA22#7762

**Review by AleGamer22 — APPROVED** [review]

**Comment by xlNightmare** [comment]
Just reviewed both, I like the first one more than the second one, @AleGamer22 You should take in mind to use more international spanish and also to be more comprehensive while doing these, they are good but they lack in comprehension, @Sonicglass Your translations are good, just pointing out you corrected some good things from the last ones, Just keep some stuff like the ones in the menu kinda native because they can be confusing for some people.

**Comment by Sonicglass** [comment]
@mty22 Sure My Krunker Ign is ´´Sonicglass´´ And my discord is Sonicglass#1532 . I will be happy to help in this translation work for the next 20 years of my life :D

**Comment by Sonicglass** [comment]
@xlNightmare  Sure man , i´ll be tranlating everything new if its possible , i will use all my English capacity to be the best espanish translator for @mty22  and Krunker in General :D

**Comment by Sonicglass** [comment]
o i forget , @mty22  if you want , and if you let me too , i will complete all the spanish code :D :D :D, seriously i love translating this stuff

**Comment by xlNightmare** [comment]
@Sonicglass @AleGamer22 Thank you so much guys for your translations, really helped a lot! Frzn is going to merge the final version of the file and it will be posted, Really appreciate the contribution! I used both of you guys changes <3

**Comment by Sonicglass** [comment]
@xlNightmare  Im happy to Help :D

**Comment by mty22** [comment]
ign/discord https://github.com/mty22/krunker.io-translations/pull/77#issuecomment-822049867

@xlNightmare all good?

**Comment by mty22** [comment]
please let me know if @AleGamer22 also contributed by providing breakdowns~

**Comment by xlNightmare** [comment]
> ign/discord [#77 (comment)](https://github.com/mty22/krunker.io-translations/pull/77#issuecomment-822049867)
> 
> @xlNightmare all good?

Im going to do a breakdown of everything today, got all info from reviewers, im just waiting til im free to do the work, and i'll review, I didnt use Alegamer's translations because they are too neutral plus they need a lot of fixes. Mostly sonicglass's one's worked best.

**Comment by mty22** [comment]
> > ign/discord [#77 (comment)](https://github.com/mty22/krunker.io-translations/pull/77#issuecomment-822049867)
> > @xlNightmare all good?
> 
> Im going to do a breakdown of everything today, got all info from reviewers, im just waiting til im free to do the work, and i'll review, I didnt use Alegamer's translations because they are too neutral plus they need a lot of fixes. Mostly sonicglass's one's worked best.

No problems. let me know when this one is ready to be merged.

If Alegamer's pull request is open still, feel free to add a comment and reference this pull request (#77) in the comment.

**Review by xlNightmare — COMMENTED** [review]
Hey there! Reviewed your translations, thank you for your support to the Spanish Project, some of your translations were used in the final file, Make sure next time use a more global spanish rather than a local one thats my only recommendation .

**Review by xlNightmare — APPROVED** [review]
File completely ready to merge. All the recommendations from the reviewers have been fixed and the file is complete. @mty22 Waiting on you

**Review by mty22 — APPROVED** [review]

**Pull request merged**
