### PR TITLE
hi.js update for v5.4.1

### PR DESCRIPTION
**Pull request by Inspire-24**
I made the updates that could be done for v5.4.1.

### CODE REVIEW

**Review by BluZed — DISMISSED** [review]
Overall it's pretty good!

**Comment by mty22** [comment]
@Inspire-24 @BluZed IGN's please!

**Comment by Inspire-24** [comment]
> 
mine- DADDY_AWM
@BluZed 's - BluZed

**Review by BluZed — APPROVED** [review]
Good work!

**Pull request merged**
