### PR TITLE
Update pl.js

### PR DESCRIPTION
**Pull request by xhg4**
In need of a reviewer, I have no contact with the person who has reviewed the last 2 or 3 pull requests

### CODE REVIEW

**Review by KaktusTranslator — CHANGES_REQUESTED** [review]
''Servers are at Max Capacity'' - Servery są pod maksymalnym obciążeniem
I would change it to Servery są Pełne 
Also i would change Zdobądź to Zdobył 
Because Zdobądź is like telling him/her to Do it And Zdobył Means he did it  
My krunker in game name: JestemKaktus
Have a nice day :)

**Comment by mty22** [comment]
@KaktusTranslator can you please provide your ign?

**Comment by xhg4** [comment]
> @KaktusTranslator can you please provide your ign?

They mentioned it earlier, once on discord and at the end of their review comment on this pull request

**Comment by xhg4** [comment]
> > @KaktusTranslator can you please provide your ign?
> 
> They mentioned it earlier, once on discord and at the end of their review comment on this pull request (JestemKaktus is their ign)

**Comment by mty22** [comment]
>  They mentioned it earlier

Missed it, thanks!

**Pull request merged**
