### PR TITLE
Update kr.js

### PR DESCRIPTION
**Pull request by Nslyc1234**
English -> Korean
lycNS#4627 

QinuF

### CODE REVIEW

**Comment by mty22** [comment]
@YuniQ152 @goonmandu can you check please?

**Review by goonmandu — CHANGES_REQUESTED** [review]
Unnecessary edits. The existing translation is effective as is.

**Comment by mty22** [comment]
Thanks @Nslyc1234 - please see the comments above.

**Comment by goonmandu** [comment]
If @YuniQ152 feels the same way, I will close the pull request.

**Comment by mty22** [comment]
> If @YuniQ152 feels the same way, I will close the pull request.

It's fine. We'll close this.

**Comment by Nslyc1234** [comment]
> Thanks @Nslyc1234 - please see the comments above.

oh.......ok

**Pull request closed without merging**
