### PR TITLE
Updated zh.js, filled in the last (new?) not translated 30 lines (v3.8.3)

### PR DESCRIPTION
**Pull request by WpyGG4125**
Finished the Chinese file and translated the last lines.
Started exactly where #104 stopped and finished all the rest.
As well fixed some missed flaws in the previous translations.
Individual work.

### CODE REVIEW

**Comment by mty22** [comment]
fixed merge conflict

pending review from second native speaker~

**Comment by Awesome-Boy-001** [comment]
@mty22 Do you mind if I can review its file?

**Comment by mty22** [comment]
Go for it. You don't need to ask. :)On 5 May 2021 00:56, Awesome-Boy-001 ***@***.***> wrote:
@mty22 Do you mind if I can review its file?

**Comment by mty22** [comment]
> @mty22 Do you mind if I can review its file?

Sure, go for it man. You don't need to ask me to review files. :)

**Review by Awesome-Boy-001 — DISMISSED** [review]
Everything looks pretty good and smooth, nothing much need to change, just need to edit few of these lines:

1. social.profile.skins.none 此用户未发布任何的皮肤
2. social.profile.games.none 此用户未发布任何的游戏地图
3. social.profile.assets.none 此用户未发布任何的地图组件
4. social.profile.mods.none 此用户未发布任何的游戏插件
5. social.market.stats.units 全球物品数
6. social.trades.out 已发送请求
7. social.trades.warning 您将不会在此交易中获得任何物品!

**Comment by WpyGG4125** [comment]
yea the first 4 lines do sound a bit more logical
for the social.trades.out, it the label for number of trades sent out (If i have understood it correctly), so i might change it but 已发送请求 also sounds a bit odd

**Comment by WpyGG4125** [comment]
For latest edit: 
Fixed grammar issues in the newest lines as well as in a few old lines
Edited certain old lines for a more fluent phrasing
Removed excessive 您s in several old lines
Changed all "Premium"s left over into 会员 for more consistency

**Comment by mty22** [comment]
@Awesome-Boy-001 all good to merge?

**Comment by Awesome-Boy-001** [comment]
> @Awesome-Boy-001 all good to merge?

I will say, yes. 👍

**Comment by mty22** [comment]
KR queued

**Pull request merged**
