### PR TITLE
Minor change in hi.js

### PR DESCRIPTION
**Pull request by TheDuce**

### CODE REVIEW

**Comment by mty22** [comment]
```
# [Hindi](https://github.com/mty22/krunker.io-translations/blob/main/hi.js) (हिन्दी)
* [BitES](https://krunker.io/social.html?p=profile&q=BitES) (BitES#7783)
* [MileRobloxn](https://krunker.io/social.html?p=profile&q=milethebot) (myul#4951)
* [Shrekajerk](https://krunker.io/social.html?p=profile&q=le_hem) (shrekajerk#2387)
* [HistoriFy](https://krunker.io/social.html?p=profile&q=HistoriFy)
* [ZEUDE](https://krunker.io/social.html?p=profile&q=zeude)
* [Keval](https://krunker.io/social.html?p=profile&q=TheDevKeval)
* [Slogllykop](https://krunker.io/social.html?p=profile&q=slogllykop)
* [Inspire-24](https://krunker.io/social.html?p=profile&q=DADDY_AWM)
* [BluZed](https://krunker.io/social.html?p=profile&q=BluZed)
* [akshutcoder](https://krunker.io/social.html?p=profile&q=akshutcoder) (Thomas Shelby#6969)
```

Any of the above able to review?

**Review by Inspire-24 — APPROVED** [review]
Looks good

**Review by BluZed — APPROVED** [review]
✔️It can be done but since 
stats.airdrops is called `KR पैकेज`
shouldn't it be stats.airdrops.stolen चुराए हुई KR पैकेज

**Review by BluZed — APPROVED** [review]
Great

**Review by DEVILisOP — APPROVED** [review]

**Comment by ThomasShelby69** [comment]
Sounds good to me.

**Review by ThomasShelby69 — APPROVED** [review]
Sounds good to me.

**Review by mty22 — APPROVED** [review]

**Comment by VantaAries** [comment]
On line 818, social.market.collectible Collectible चीज  can be changed to " social.market.collectible संग्रहणीय वस्तु "

**Pull request merged**
