### PR TITLE
Minor edits to kr.js

### PR DESCRIPTION
**Pull request by apinklover**
@mty22 @YuniQ152 @tr0922 @dojinshi 
Remove ambiguity with 을/를, 이/가 and 은/는
"Casualized" some terms such as 자본, 수신 etc.
Changed "거래" with its transliterated version "트레이드" as the latter is what the overwhelming majority of Korean players refer to trading as (Korean translations didn't exist back in May 2020 when trading was first introduced)

### CODE REVIEW

**Comment by YuniQ152** [comment]
It seems to need to change "발송됨" to "보냄" in Line 769. Other thing is great <3

**Comment by mty22** [comment]
Actually, that reminds me. There were quite a few sentences in the Korean language that has full stops at the end, where the English language file did not.

It should be simple enough to fix in an automated way. I'll check it later (just noting it here so I don't forget).

**Comment by mty22** [comment]
Fixed merge conflict, also fixed up some general issues (https://github.com/mty22/krunker.io-translations/pull/168/commits/ab2743b541d3189ea0cb25e6617039a82e59c5fe) as I mentioned in my previous comment.

Pinged @apinklover on Discord about @YuniQ152's comment, then we're good to merge once fixed.

Thanks guys!

**Comment by apinklover** [comment]
> It seems to need to change "발송됨" to "보냄" in Line 769. Other thing is great <3

@YuniQ152 Yep! Looks good.

**Comment by mty22** [comment]
> > It seems to need to change "발송됨" to "보냄" in Line 769. Other thing is great <3
> 
> @YuniQ152 Yep! Looks good.

OK, I'll update it then merge on your behalf.

**Pull request merged**
