### PR TITLE
nl.js - Minor fixes and added new translations. DUTCH (v3.8.2)

### PR DESCRIPTION
**Pull request by CorruptSausage**
Minor fixes
Added new translations.

### CODE REVIEW

**Comment by mty22** [comment]
Thanks for the Pull Request! Just need a second person to review.

Any of these players would be ideal:

Semliot (Semliot#0070), NickAuthentic (nickauthentic#9999), Gluzly (gluzly#9999), AdoreMe (AdoreMe#0082)

**Comment by gluzly** [comment]
Me and Corrupt had already decided that the changes made were good.

**Review by nickauthentic — COMMENTED** [review]
Hi,
I think some of your translations are quite good, only a few are incorrect.
I think it would be better if we keep "mods" the same, "Modificaties" sounds weird.
It's also better to keep "Trades" the same, "aanbiedingen", "Aanbod" and "Ruil" don't sound right.

- Nick

**Comment by CorruptSausage** [comment]
> .
Changed.

**Review by mty22 — APPROVED** [review]

**Comment by mty22** [comment]
discord CorruptSausage#7371
ign CorruptSausage

**Comment by mty22** [comment]
role sorted, kr queued.

**Pull request merged**
