### PR TITLE
A Few Lines Updated it.js

### PR DESCRIPTION
**Pull request by Kyxul**

### CODE REVIEW

**Comment by mty22** [comment]
Very nice! Just need a native speaker to review now!

https://github.com/mty22/krunker.io-translations/blob/main/CONTRIBUTORS.md#italian-italiano

Feel free to ping someone from that list.

**Comment by Kyxul** [comment]
@colpiffero

**Comment by mty22** [comment]
Still need native speaker to review. :(

**Comment by mty22** [comment]
bonus kr up for grabs for reviewer

**Comment by mty22** [comment]
treating as abandoned, still need native reviewer. re-open if you wish to review.

also see https://github.com/mty22/krunker.io-translations/pull/481

**Pull request closed without merging**
