### PR TITLE
Update pr.js with en.js updates (v5.4.4)

### PR DESCRIPTION
**Pull request by Harpicc**

### CODE REVIEW

**Comment by mty22** [comment]
@xlNightmare any chance you can review please?

**Comment by mty22** [comment]
Merge conflict fixed..

**Comment by mty22** [comment]
Nightz said he has a contact who can review.

**Comment by mty22** [comment]
@xlNightmare ?

**Comment by mty22** [comment]
will pay bonus kr, still needs review!

**Review by xlNightmare — COMMENTED** [review]
Review by myself is done and looks good to go, a native is on progress on reviewing aswell, will push out the final change soon,

**Review by vecmath — CHANGES_REQUESTED** [review]
line 980, 978: change "expluso" for "expulso".
line 925: change to "Jogo em progresso".
line 912: chall.name.lns Matar {0} com tiros de longa distancia {1}
line 904: chall.name.ls Matar {0} com tiros na perna {1}
line 905: chall.name.tmk Matar {0} atirando a faca {1}
line 906: chall.name.fb Obter {0} primeiras mortes {1}

**Comment by xlNightmare** [comment]
Update pushed, ready to go, thanks for both of your collaboration @Harpicc @vecmath

**Comment by mty22** [comment]
Nice, thanks! @vecmath can you let me know what your IGN is please?

**Comment by xlNightmare** [comment]
> Nice, thanks! @vecmath can you let me know what your IGN is please?

@mty22 his ign is Diamba1 ^^

**Review by 1opez — APPROVED** [review]

**Review by MLKEDX — APPROVED** [review]
Looks good!

**Comment by mty22** [comment]
kr queued

**Pull request merged**
