### PR TITLE
Fr.js

### PR DESCRIPTION
**Pull request by Aztecsy**
small update on french file

### CODE REVIEW

**Comment by mty22** [comment]
Nice, thanks for that.

Please note that there's an existing PR in ahead of yours: https://github.com/mty22/krunker.io-translations/pull/390

Will review in order.

**Comment by mty22** [comment]
Also, please feel free to update https://github.com/mty22/krunker.io-translations/blob/main/CONTRIBUTORS.md

(lets me know your IGN)

**Comment by Aztecsy** [comment]
Hey! Just wanted to add that on top of actually implementing a ton of
elements and correcting previous mistakes, I put in common the drafts of
other people to basically have an all in 1 and better.

Ign : Maximetemange

**Comment by mty22** [comment]
Noted, thank you. We still operate in order of PR just to maintain fairness.

**Comment by Aztecsy** [comment]
[image: image.png]

Do I add my name like so?

**Review by MLKEDX — COMMENTED** [review]
The rest I think is correct so it's just something small but when you translate "2x Class XP" to "Double XP" you leave out the word "class", some people won't know which xp it's about so I would change:
(923) event.doubleXP Double XP activé pour cette partie
to
(923) event.doubleXP Double catégorie XP activé pour cette partie

**Comment by mty22** [comment]
Hi @Aztecsy - I recently merged PR https://github.com/mty22/krunker.io-translations/pull/390

Can you please review the merge conflicts on your changes and ping me either in Discord or here once done?

https://github.com/mty22/krunker.io-translations/pull/414/conflicts

I'll close this PR for now (re-open when ready)

**Comment by Aztecsy** [comment]
@mty22 Read over the whole thing over, looks great to me!

**Pull request closed without merging**
