### PR TITLE
Update zh.js (v3.8.1)

### PR DESCRIPTION
**Pull request by UnityEthan**

### CODE REVIEW

**Comment by UnityEthan** [comment]
Added more translations, DM Stonkman#0948 for details (i forgot to publish the title)

**Comment by mty22** [comment]
Hi @UnityEthan - thanks for the Pull Request.

There's an existing pull request for `zh.js`, can you please have a look and to compare your changes to the other pull request?

Click here: https://github.com/mty22/krunker.io-translations/pull/82/files

**Comment by mty22** [comment]
Actually, @UnityEthan - we'll keep this one open for the moment.

**Comment by UnityEthan** [comment]
hey man, idk how this thing works atm. is there anything i can help with

**Comment by UnityEthan** [comment]
> Hi @UnityEthan - thanks for the Pull Request.
> 
> There's an existing pull request for `zh.js`, can you please have a look and to compare your changes to the other pull request?
> 
> Click here: https://github.com/mty22/krunker.io-translations/pull/82/files

Can I add your discord? I checked the existing pull request but there are still a lot of things to improve.

**Comment by UnityEthan** [comment]
hey matt I just published my second version with more translations. I would
appreciate it if you can take a look at it and merge my translation with
the existing ones. thanks

**Comment by mty22** [comment]
New PR from the same user: https://github.com/mty22/krunker.io-translations/pull/104

**Pull request closed without merging**
