### PR TITLE
Update kr.js (v5.4.1)

### PR DESCRIPTION
**Pull request by YuniQ152**
v5.4.1에서 추가된 내용들을 번역했습니다. 챌린지 관련 내용(893~925번째 줄)은 문법 관련 문제(#296)로 번역하지 않고 영어 그대로 남겨뒀습니다. 

---
Translated new contents for v5.4.1. Challenge related sentences (line 893-925) were not translated due to grammar issue(#296).

### CODE REVIEW

**Comment by mty22** [comment]
lol, sorry @goonmandu - @YuniQ152 is too quick for ya.

Can you review please? :)

**Comment by mty22** [comment]
I've applied a fix, can you please review your respective language and implement? https://github.com/mty22/krunker.io-translations/commit/5ec0f43d446e618fd7d0a446ba2fbcb9138eacd4

**Comment by goonmandu** [comment]
I'll take a look in a couple of hours—got a physics lecture to attend.

**Comment by mty22** [comment]
@goonmandu let us know when good to go!

**Comment by goonmandu** [comment]
@YuniQ152 @mty22 
Looks okay, just some semantic/vocabulary suggestions based on translation style and minor errors:

Line 462:
Change `편집기` to `맵 에디터`, since the latter was more commonly used in the translated patch notes.

Line 510:
Change `휠` to `메뉴`, since Korean players might not know what "wheel" is, but "menu" is straightforward and is a widely-known English word by Korean speakers.

Line 545:
Finish the unfinished translation: `도발 (이게 뭐야?)`

Line 546:
Finish the unfinished translation: `도발 (지금 당장!)`

Line 614:
The game is hardcoded to append the item name at the end of the translation. To make the translation as compatible with the code as possible, I suggest changing it to this: `{0}{1}님이 아이템을 찾음: `

Line 676:
Change it to `서버 수용량이 가득 찼습니다` (Without the period. The period is off-looking because of the font discrepancy)

Line 839:
Change `유용한 신고` to `유용한 신고 수`

Line 863:
Change `파기` to `파괴`. The former means "to break a contract or a promise," where the latter correctly means "to destroy."

**Comment by YuniQ152** [comment]
@goonmandu님의 의견을 반영하여 수정하고, 이와 관련된 내용도 일관성있게 변경했습니다.

**Review by goonmandu — APPROVED** [review]
@mty22 @YuniQ152
I approve of the changes!

**Pull request merged**
