### PR TITLE
Update fr.js

### PR DESCRIPTION
**Pull request by enygmate**
I believe this PR fixes everything from [issue 337](https://github.com/mty22/krunker.io-translations/issues/337) 

A lot (70-80%) of the translations are from @Kason19's PRs
I think I have translated all the remaining bits of english

### CODE REVIEW

**Comment by enygmate** [comment]
I suck at github so I don't know who to request review from @Kason19 and @nerrrrrrrdy but if you guys see it your review is welcomed

**Comment by nerrrrrrrdy** [comment]
Line 924's original translation was kept and needs to be removed for the translation to properly work
Line 969 is untranslated, but i can suggest "Doit jouer à au moins une manche"

**Comment by enygmate** [comment]
Fixed

**Comment by nerrrrrrrdy** [comment]
Looks great!

**Comment by Kason19** [comment]
I think this looks good. By the way, i'm very new to Github to idk much about this. Also, I did my pull request in the middle of the night, so if you find something better, just add it (or rephrase).

**Comment by Kason19** [comment]
I think at line 970, instead of "Attendez que le match commence pour déclarer forfait", "Veuillez attendre que le match commence pour déclarer forfait" might be slightly better.

**Comment by enygmate** [comment]
I didn't really know what this string referred to so I translated it like that, it's probably better as you say

**Comment by mty22** [comment]
Thanks everyone.

@Kason19 what is your ign?

**Comment by mty22** [comment]
@notJake34 taking into account of your two existing PRs:

https://github.com/mty22/krunker.io-translations/pull/349
https://github.com/mty22/krunker.io-translations/pull/323

Can you please review this PR and let me know if there's any overlapping work?

Thanks!

**Comment by mty22** [comment]
@nerrrrrrrdy likewise as above with https://github.com/mty22/krunker.io-translations/pull/373/files

**Comment by Kason19** [comment]
> Thanks everyone.
> 
> @Kason19 what is your ign?
hi, it is "---pro"

**Comment by notJake34** [comment]
Ligne 968: Suspect trouvé. Spectating: {0}, Spawned: {1}, Name: {2}
Devrait être: Suspect trouvé. Observer: {0}, Spawned: {1}, Nom: {2}
Idk what spawned is suppose to be...

**Comment by notJake34** [comment]
Rest looks good tho

**Comment by notJake34** [comment]
> @notJake34 taking into account of your two existing PRs:
> 
> #349 #323
> 
> Can you please review this PR and let me know if there's any overlapping work?
> 
> Thanks!

Sorry for being late, I was busy with some stuffs lately, closed both of them as the file made by eny looks good.

**Comment by 22x92** [comment]
> Ligne 968: Suspect trouvé. Spectating: {0}, Spawned: {1}, Name: {2}
> Devrait être: Suspect trouvé. Observer: {0}, Spawned: {1}, Nom: {2}
> Idk what spawned is suppose to be...

I think that Spawned can be translated by "réapparition" or "apparition"

**Comment by mty22** [comment]
is this good to merge?

**Comment by Kason19** [comment]
> is this good to merge?

Some of the changes are good, for example "a été exclu" instead of "a été expulsé" may be better, but most of it was already done by enygmate in this pull request. Let's wait for the other people's opinion.

**Review by MLKEDX — APPROVED** [review]

**Comment by mty22** [comment]
@nerrrrrrrdy can you reach out to me with your IGN please? (ping or dm)

**Pull request merged**
