### PR TITLE
Updage fr.js v5.4.5

### PR DESCRIPTION
**Pull request by 192alt**

### CODE REVIEW

**Comment by Aztecsy** [comment]
The last lines are grammatically incorrect. "Etait arrete" is active voice but the hacker is not the one doing the action. "etait kicked" is the same problem and "kicked" isnt a french word. I don't want to review every single line but there is to many mistakes. I remade the whole thing without mistakes.

**Comment by 192alt** [comment]
i only changed the etait parts there cause i didnt know the other parts

**Comment by mty22** [comment]
so whats the verdict? are you making changes @192alt ?

**Comment by 192alt** [comment]
wdym? yes i made changes to the thing that i thought were correct.

**Comment by mty22** [comment]
Hello! I've recently merged another PR (https://github.com/mty22/krunker.io-translations/pull/390), can you please rebase to fix merge conflicts and push changes again for review?

**Pull request closed without merging**
