### PR TITLE
Update de.js

### PR DESCRIPTION
**Pull request by traconixx**
updated some things that sounds better now

### CODE REVIEW

**Comment by mty22** [comment]
Still needs review.

**Comment by mty22** [comment]
@AndoKPD can you have a look please?

**Review by AndoKPD — APPROVED** [review]
Changes look good. The word Editor is actually used by GTA V and Forza Horizon 5 in german language. https://github.com/mty22/krunker.io-translations/blob/main/de.js#L465 needs to be changed to Editor aswell, then you can merge.

**Comment by mty22** [comment]
@traconixx can you please review @AndoKPD 's comment and update the PR?

**Review by AndoKPD — APPROVED** [review]
Ready to be merged

**Review by AndoKPD — APPROVED** [review]
Ready to be merged

**Review by MLKEDX — APPROVED** [review]
Good

**Comment by mty22** [comment]
@traconixx please reach out to me with your IGN (`frzn#1030`), or post here.

**Comment by traconixx** [comment]
@mty22 sent you a friend req on dc but my ign is "GM_Senpai"

**Pull request merged**
