### PR TITLE
Minor changes in hi.js - by -devil#0001

### PR DESCRIPTION
**Pull request by DEVILisOP**
updated 928th line

### CODE REVIEW

**Review by TheDuce — APPROVED** [review]
good to merge

**Comment by notanerdstudent** [comment]
sounds good.

**Comment by ThomasShelby69** [comment]
Looks good.

**Review by ThomasShelby69 — APPROVED** [review]
Looks good.

**Review by BluZed — APPROVED** [review]
great

**Comment by mty22** [comment]
see https://github.com/mty22/krunker.io-translations/pull/458

**Pull request closed without merging**
