### PR TITLE
Update pl.js (v4.0.9)

### PR DESCRIPTION
**Pull request by xhg4**
Git seems to have messed something up (it says that all lines were changed even tho I've only changed the lines that were added to en.js from 3.8.6 to 4.0.9) but I've checked everything and the text itself is completely fine

(Note to anyone who will be reviewing this): only lines 94, 101, 180, 265, 305, 360-361, 470-477, 487-490, 581-582, 676, 689-692 and 784 were actually changed in this PR
Well, time to wait for someone to review this

### CODE REVIEW

**Comment by xhg4** [comment]
Now I see why it says that all lines were changed were that wasn't actually the case
The "+ ';" was changed to "- ';" (not by me, it was like that when I synced my fork) which automatically changed the - in front of all the lines to +
Idk if that's an issue, if it is, then please let me know and I'll change it asap

**Comment by mty22** [comment]
> Git seems to have messed something up (it says that all lines were changed even tho I've only changed the lines that were added to en.js from 3.8.6 to 4.0.9) but I've checked everything and the text itself is completely fine

This happened because I ran `dos2unix` on the file, which removes `^M` from end of line (carriage return character).

It just 'replaces' the existing file with a 'new' copy of the data (minus the carriage return character).

I've since fixed this up in in commit https://github.com/mty22/krunker.io-translations/commit/6127b71c6323d478ce7982e6e8fe32a581ca51c6 -- instead of running it on the file, I do it per line as I rebuild  language files.

Also, thank you for the PR - I'll invite you as a contributor as I consider you the owner of `pl.js` at this stage. :) Just need a review and it'll be good to merge.

**Comment by xhg4** [comment]
> > Git seems to have messed something up (it says that all lines were changed even tho I've only changed the lines that were added to en.js from 3.8.6 to 4.0.9) but I've checked everything and the text itself is completely fine
> 
> This happened because I ran `dos2unix` on the file, which removes `^M` from end of line (carriage return character).
> 
> It just 'replaces' the existing file with a 'new' copy of the data (minus the carriage return character).

Ooh, okay, that makes sense

> I've since fixed this up in in commit https://github.com/mty22/krunker.io-translations/commit/6127b71c6323d478ce7982e6e8fe32a581ca51c6 -- instead of running it on the file, I do it per line as I rebuild  language files.
> 
> Also, thank you for the PR - I'll invite you as a contributor as I consider you the owner of `pl.js` at this stage. :) Just need a review and it'll be good to merge.
> 
Well, thanks I guess haha

**Comment by isoriFPS** [comment]
I can approve that the PR is fine, everything is perfect.

**Comment by xhg4** [comment]
@mty22 PR ready to be merged

**Comment by mty22** [comment]
@isoriFPS can you send me your IGN please! (tag me here or DM in discord  - frzn#1030)

**Pull request merged**
