### PR TITLE
GoonMandu's alternate pull request to kr.js (choose mine or @tr0922's for final merge)

### PR DESCRIPTION
**Pull request by apinklover**
Didn't particularly agree with the ongoing pull request and I also worked on minor changes to previously translated files, which would be too tedious to suggest to the current @tr0922's pull request.

### CODE REVIEW

**Comment by tr0922** [comment]
@apinklover I think it's good! tho you were talking about formality, ig it has to be formal but a little smooth on the other side, based on your translations :)

**Comment by mty22** [comment]
@apinklover I can't really choose as I don't understand Korean. I need to rely on you guys to let me know what is good and what needs improvement.

**Comment by apinklover** [comment]
> @apinklover I think it's good! tho you were talking about formality, ig it has to be formal but a little smooth on the other side, based on your translations :)

Can you give me some examples how you'd change it?

**Comment by tr0922** [comment]
@apinklover Check zVader's and mine, Vader already made almost perfect edits! So I edited that again, so just go to my pull and see for yourself :D

**Comment by mty22** [comment]
https://github.com/mty22/krunker.io-translations/pull/95

see comments here, closing this PR

**Pull request closed without merging**
