### PR TITLE
Update fi.js

### PR DESCRIPTION
**Pull request by DetectGamer**
So I now just pressed the edit button and edited all the terms that needed translation. This was how it was done in a guide, I think it's the correct way. Tell me if it's wrong.
(Finnish translation update)

### CODE REVIEW

**Comment by DetectGamer** [comment]
My IGN is DetectGamer

**Comment by mty22** [comment]
nice!

@SirJypa can you review please, if time permits?

**Comment by ItsPiki** [comment]
> nice!
> 
> @SirJypa can you review please, if time permits?

I could also do it.

**Review by ItsPiki — DISMISSED** [review]
All good. No mistakes and spelling is correct.

**Comment by mty22** [comment]
Fixed up merge conflicts

**Pull request merged**
