### PR TITLE
Spanish updates (v3.8.2)

### PR DESCRIPTION
**Pull request by xlNightmare**
Updated 3.8.2 Based on 3.8.2 Duplicate Rebuild

### CODE REVIEW

**Review by csrye — DISMISSED** [review]
Reviewed and ready for merging

**Review by Aby3kr — APPROVED** [review]
Reviewed and ready to merge

**Review by csrye — APPROVED** [review]
Reviewed and ready for merging

**Review by mty22 — APPROVED** [review]

**Comment by mty22** [comment]
Will merge once I am home.

**Pull request merged**
