### PR TITLE
Traditional Chinese Language file

### PR DESCRIPTION
**Pull request by WpyGG4125**
Traditional Chinese translation 100% complete
The file just exists to be on hold for more translators, please don't close.

**Corrections are currently being made**

### CODE REVIEW

**Comment by mty22** [comment]
Very nice! This one isn't approved yet, although it likely will be (I need to check in with Dev's still). Thank you for the work.

In the mean time, are you able to find a native speaker to review?

**Comment by WpyGG4125** [comment]
Yes I was planning to get the other 2 translators to review

**Review by RIFLEJI — COMMENTED** [review]
I guess it's done

**Review by Therealzz — COMMENTED** [review]
There are some Simplified Chinese characters inside the translation.
Some wordings in the translation don't match the convention of zh-tw and zh-hk localization.

(Part of the) Examples:
后 should be 後
menu.btn.invite.clicked 已復制 should be 已複製
generic.loading 加載中... would be better if using 載入中... or 正在載入..
generic.search 搜索 would be better if using 搜尋
generic.default 默認 would be better if using 預設
generic.logout.sessions 從所有設備登出 would be better if using 從所有裝置上登出
generic.name 姓名 is kinda weird inside a game context
and more...

so.. I don't think translation quality is up to a native level standard
it seems like zh-cn and being google translated from simplified chinese.

Discord ID: zzdev#6948

**Comment by WpyGG4125** [comment]
> There are some Simplified Chinese characters inside the translation.
> Some wordings in the translation don't match the convention of zh-tw and zh-hk localization.
> 
> (Part of the) Examples:
> 后 SHOULD BE 後
> menu.btn.invite.clicked 已復制 SHOULD BE 已複製
> generic.loading 加載中... would be better if using 載入中... or 正在載入..
> generic.search 搜索 would be better if using 搜尋
> generic.default 默認 would be better if using 預設
> generic.logout.sessions 從所有設備登出 would be better if using 從所有裝置上登出
> generic.name 姓名 is kinda weird inside a game context
> and more...
> 
> so.. I don't think translation quality is up to a native level standard
> it seems like zh-cn and being google translated from simplified chinese.
> 
> Discord ID: zzdev#6948

mhm yeah i missed out some stuff from the file, so there might be issues
the things with logout.sessions and generic.name is just inherited from the original file, I could change them if you want but they are more like preferences.
Ill try to fix these issues, thanks for the comment

**Comment by mty22** [comment]
@Therealzz Thank you for the feedback. Much appreciated.

**Comment by mty22** [comment]
@WpyGG4125 for now, I'll close this pull request as I feel like a lot of work needs to be done. Create a new one when you're ready.

A strong reminder that the quality needs to be at native level as it will be viewed by thousands.

**Pull request closed without merging**
