### PR TITLE
Update kr.js

### PR DESCRIPTION
**Pull request by Baw-Appie**

### CODE REVIEW

**Review by apinklover — COMMENTED** [review]
Line 646 - Change it to a more general term, for example "데스 캠" or "처치 영상" (with the latter being used in Overwatch)
Line 664 - Minimize the usage of English words in Korean translations, "시험 모드"
Line 665 - The term "class" is now referred to as "클래스" in the Korean community as well, let's change it to "클래스 제한"

Others look fine, also at least include a short description in your future pull requests if you plan on continuing to contribute.

**Review by apinklover — APPROVED** [review]
Approved. Nice work!

**Comment by mty22** [comment]
kr queued

**Comment by apinklover** [comment]
merged poggers

**Pull request merged**
