### PR TITLE
translated the challenges for tr.js

### PR DESCRIPTION
**Pull request by lelprodude**
not sure if im supposed to put this here but my discords lelprodude#3795 and my krunker ign is lelprodude

### CODE REVIEW

**Comment by lelprodude** [comment]
the 'da part that comes after the map name can change depending on the map

**Comment by mty22** [comment]
nice, thank you. pending review.

**Comment by mty22** [comment]
@SecretMember are you able to have a look, please? :)

**Comment by mty22** [comment]
@SecretMember sent me a DM on Discord advising all is well.

**Pull request merged**
