### PR TITLE
Update zh.js & zhtr.js (v5.4.2)

### PR DESCRIPTION
**Pull request by 0v0katai**
**Workload breakdown**
- zh.js
self-work + borrowed some translations from zhtr.js with terminology tweaks

- zhtr.js
50% 0v0katai [IGN 0v0katai, Discord ID 0v0katai#1265]
50% The1der4 [IGN 1der4, Discord ID 1der4#8959]

### CODE REVIEW

**Comment by 0v0katai** [comment]
Changed "您" to "你" in both files after having a discussion with 1der4. The reason is no need to be too formal + 您 is used to refer to the seniors

**Review by YureiOwO — CHANGES_REQUESTED** [review]
settings.audio.input 音訊輸入 

windows.clan.leave 你確定要離開此戰隊嗎？

windows.clan.delete 你確定要解散此戰隊嗎？

social.market.gift.msg 講點什麼呢...

settings.quality.mflash 槍口閃光

settings.chat.chatFilter 髒話過濾

**Review by YureiOwO — CHANGES_REQUESTED** [review]
settings.audio.input 音訊輸入 

windows.clan.leave 你確定要離開此戰隊嗎？

windows.clan.delete 你確定要解散此戰隊嗎？

social.market.gift.msg 講點什麼呢...

settings.quality.mflash 槍口閃光

settings.chat.chatFilter 髒話過濾

**Review by Awesome-Boy-001 — COMMENTED** [review]
Overall, it looks great. Here are some suggestions:

**zh.js** (Please also apply these changes into "zhtr.js" file with traditional Chinese font if possible)
130 settings.chat.chatFilter 不当语言过滤（仅限英文）
308 settings.gameprivacy.custom 显示特殊徽章
486 windows.loadout.badge 特殊徽章
545 windows.controls.taunt4 嘲讽（这到底是什么鬼？）
595 windows.clans.login 登录以创建或加入公会！
598 windows.store.agree 确认购买即表示你同意 {0} 条款及细则
676 matchmaker.NoAvailableServers 总体服务器负载已达到上限
682 error.extentions 如果你有任何浏览器插件，请禁用它们
863 item.sell.destroy 你确定要毁坏 {0} 吗？

**Comment by 0v0katai** [comment]
>130 settings.chat.chatFilter 不当语言过滤（仅限英文）
脏话 is the literal translation for "profanity". ^^

>308 settings.gameprivacy.custom 显示特殊徽章
>486 windows.loadout.badge 特殊徽章
Oh yes, this kind of badge is not customizable by player so 特殊 is more appropriate.

>545 windows.controls.taunt4 嘲讽（这到底是什么鬼？）
This is also OK if you want a less offensive tone.

>595 windows.clans.login 登录以创建或加入公会！
Nice catch.（或 is more appropriate indeed）

>598 windows.store.agree 确认购买即表示你同意 {0} 条款及细则
I am not sure on this one because in en.js, {0} is sticked to "Terms & Conditions". @mty22 Can you confirm this one?

>676 matchmaker.NoAvailableServers 总体服务器负载已达到上限
I think translating "No available servers"（当前没有任何空闲的服务器） instead of "Servers are at max capacity" would be much clearer.

>682 error.extentions 如果你有任何浏览器插件，请禁用它们
Ok.

>863 item.sell.destroy 你确定要毁坏 {0} 吗？
分解 is more appropriate as you can get something from doing so.

Oh, and also I just realized "medals" in Krunker means "kill awards" like [this](https://imgur.com/a/B99KqJT), so 奖牌 here is too general. 击杀奖牌 would be more specific.

**Comment by mty22** [comment]
> I am not sure on this one because in en.js, {0} is sticked to "Terms & Conditions". @mty22 Can you confirm this one?

I checked, this is intended.

**Comment by mty22** [comment]
excellent work as usual.

@Awesome-Boy-001 when you're happy, please let me know and we can merge it in.

I'll sort badges etc.

**Comment by Awesome-Boy-001** [comment]
@mty22 Yes, I'm very happy. I see no problems in the file so you may merge it in. Thank you.

**Review by DevChrisChan — CHANGES_REQUESTED** [review]
`stats.airdrops.stolen 偷取空投次數` should be `stats.airdrops.stolen 偷取 KR 空投次數`?

**Comment by 0v0katai** [comment]
> `stats.airdrops.stolen 偷取空投次數` should be `stats.airdrops.stolen 偷取 KR 空投次數`?

@DevChrisChan Well 1) The English term is just "Airdrops stolen" and for consistency reason I do not include "KR" here, and 2) There is also another type of airdrop that contains Junks. Stealing it also counts to this stat so putting "KR" here is inaccurate.

**Comment by DevChrisChan** [comment]
ah. also line 107 `settings.client.discordRPC Discord 豐富狀態` should be `settings.client.discordRPC Discord 遊戲狀態`

**Comment by DevChrisChan** [comment]
and also (sorry I'm new, I'm not sure if I'm contributing to this correctly) `generic.follow 追隨` and `generic.unfollow 取消追隨` should be `generic.follow 追蹤` and `generic.unfollow 取消追蹤`.

**Comment by DevChrisChan** [comment]
Some translation suggestions:
[zhtr]:
Line 107: `settings.client.discordRPC Discord 豐富狀態` should be `settings.client.discordRPC Discord 遊戲狀態`

Line 38: `generic.follow 追隨` should be `generic.follow 追蹤`

Line 39: `generic.unfollow 取消追隨` should be `generic.unfollow 取消追蹤`

Line 40: `generic.followers 個追隨者` should be `generic.followers 個追蹤者`

Line 41: `generic.following 個追隨中` should be `generic.following 個追蹤中`

**Comment by 0v0katai** [comment]
> ah. also line 107 `settings.client.discordRPC Discord 豐富狀態` should be `settings.client.discordRPC Discord 遊戲狀態`

Official Discord admin refers it as 豐富狀態 (Rich Presence）
https://support.discord.com/hc/zh-tw/articles/115001557452-%E9%81%8A%E6%88%B2%E9%82%80%E8%AB%8B%E5%92%8C%E8%A9%B3%E7%B4%B0%E7%8B%80%E6%85%8B-%E8%B1%90%E5%AF%8C%E7%8B%80%E6%85%8B-

> Line 39: generic.unfollow 取消追隨 should be generic.unfollow 取消追蹤
Line 40: generic.followers 個追隨者 should be generic.followers 個追蹤者
Line 41: generic.following 個追隨中 should be generic.following 個追蹤中

Hmm, quite unnecessary as both have the same meaning.

> Line 69: popup.checkpoint 存檔點！ should be popup.checkpoint 關卡！`.
Well 關卡 means level and isn't necessarily equivalent to checkpoint which lets you respawn in the saved position.

**Comment by mty22** [comment]
@0v0katai this good to merge?

**Pull request merged**
