### PR TITLE
Big update for Russian language

### PR DESCRIPTION
**Pull request by Loreos7**
Revised the full file and added new translations from abandoned https://github.com/mty22/krunker.io-translations/pull/422

### CODE REVIEW

**Comment by CalibriLight** [comment]
ух ты ну я лох думал все перевел

**Comment by mty22** [comment]
This is huge. Good job.

Need a native speaker to review.

**Review by realTiXoNyA — APPROVED** [review]
I would not agree with many of the corrections, since they are minimal and change the size of a letter in one of the words, but this does not distort the essence of the translation. New translation strings are correct, the translation is ready for the game

**Review by ghost — APPROVED** [review]
The new translation strings are correct, and the corrections in the existing ones are also good, although some of them weren't necessary (changes like `е` -> `ё`)

**Pull request closed without merging**
