### PR TITLE
Turkish Create tr.js (v3.8.1)

### PR DESCRIPTION
**Pull request by SecretMember**

### CODE REVIEW

**Comment by mty22** [comment]
@KenTechYT and @hon0urdy - any chance you guys can a look at the 'Files Changed' tab and review @SecretMember 's pull request?

This language isn't approved yet, although it may be used in future.

**Comment by SecretMember** [comment]
Contributions:

SecretMember#0099 (25%), NathanNorth#4365 (25%), W_O#1903 (25%), hon0urdy#5024 (25%)

**Comment by mty22** [comment]
Contributors IGNs:

```[10:50 PM] SecretMember: https://krunker.io/social.html?p=profile&q=SecretMember (SecretMember)
https://krunker.io/social.html?p=profile&q=Axima (NathanNorth)
https://krunker.io/social.html?p=profile&q=Winner_Ogün (W_O)
https://krunker.io/social.html?p=profile&q=onurongunnn (hon0urdy)```

**Comment by AnatomisPerfect** [comment]
I pleasurely looked into the list. My native language is Turkish and I can speak English very well in my opinion. I can't really see any mistake in the list that would break the game. It's looking fresh! Would love to see it in game. :)

**Review by mty22 — APPROVED** [review]

**Comment by mty22** [comment]
Just a note with this one - it wasn't approved, so no KR will be distributed unless we add it to the game.

**Comment by mty22** [comment]
> Contributions:
> 
> `SecretMember#0099 (25%), NathanNorth#4365 (25%), W_O#1903 (25%), hon0urdy#5024 (25%)`

Discord roles sorted.

**Pull request merged**
