### PR TITLE
New translations for it.js

### PR DESCRIPTION
**Pull request by MrGira**
Added new translations, @colpiffero could you please review?

### CODE REVIEW

**Comment by mty22** [comment]
@MrGira does this wrap in changes proposed in https://github.com/mty22/krunker.io-translations/pull/291 ?

also are you able to find a reviewer?

**Comment by MrGira** [comment]
@mty22 No I didn't include those since I proposed some changes to the original translator. I can add them if necessary. 
I asked @colpiffero of he could review this one, but I can always find someone else if necessary.

**Comment by mty22** [comment]
I've applied a fix, can you please review your respective language and implement? https://github.com/mty22/krunker.io-translations/commit/5ec0f43d446e618fd7d0a446ba2fbcb9138eacd4

**Comment by mty22** [comment]
> @mty22 No I didn't include those since I proposed some changes to the original translator. I can add them if necessary. I asked @colpiffero of he could review this one, but I can always find someone else if necessary.

OK, no problems. If the other translator does not reply, we'll treat the PR as abandoned and you may implement the changes.

**Comment by MrGira** [comment]
@mty22 I incorporated the translations made for #291

**Comment by colpiffero** [comment]
I've reviewed everything, nothing to change

**Pull request merged**
