### PR TITLE
fr.js

### PR DESCRIPTION
**Pull request by notJake34**
Most things, I suggested were added, added some things that were left.
Also, match is an anglicism, partie should be prioritized.

### CODE REVIEW

**Review by enygmate — COMMENTED** [review]
Since Partie is a feminine word, in this case it would be spelled like that.
generic.matchover PARTIE TERMINÉE
generic.matchaband PARTIE ABANDONNÉE

Also I feel like Match is a very commonly used anglicism that everyone understands as we use it for sports as well. So, I don't know if it really needs a translation. Both work

**Comment by notJake34** [comment]
> Since Partie is a feminine word, in this case it would be spelled like that. generic.matchover PARTIE TERMINÉE generic.matchaband PARTIE ABANDONNÉE
> 
> Also I feel like Match is a very commonly used anglicism that everyone understands as we use it for sports as well. So, I don't know if it really needs a translation. Both work

Ye I understand ur point

**Comment by mty22** [comment]
based on @enygmate's comment, I assume we're not going ahead with this PR?

**Comment by mty22** [comment]
aggregate https://github.com/mty22/krunker.io-translations/pull/390

**Pull request closed without merging**
