### PR TITLE
Update kr.js-tr0922

### PR DESCRIPTION
**Pull request by tr0922**
Yeah, I worked it out how to upload dis :/
I added some missing translations and I edited it a little bit.
IGN is tr0922 >:)

### CODE REVIEW

**Comment by mty22** [comment]
@YuniQ152 can you have a look at this one please?

**Comment by apinklover** [comment]
@tr0922 translations are pretty inconsistent, are you sure you proofread?
I'll be working on my version of the new changes then we can prolly pick and choose which one of our versions will make it in the final merge

**Comment by apinklover** [comment]
Have a look at my take on the updates in the kr.js file in my fork: https://github.com/apinklover/krunker.io-translations/blob/main/kr.js
Alternatively, download the file yourself:
[kr.js.txt](https://github.com/mty22/krunker.io-translations/files/6322657/kr.js.txt)

**Comment by tr0922** [comment]
Ohhh Ok :D
I didn't know that I was inconsistent :/ sorry
So, I guess we're going with yours, definitely!

**Comment by tr0922** [comment]
@apinklover heyy I just checked out your version, and it looks POG!
but idrk abt the tone, cuz it's just rly formal :/
Translations are supposed to be understandable, whether or not the player is young or old.
So I just wanted to edit the translations in a tone that's friendly and more easily acceptable.
(it's still a game)

**Comment by apinklover** [comment]
Well, it wouldnt be a problem if the prior translations had been in a more casual tone, but that's not the case here. I would actually argue that having translations in such a casual voice would unintentionally generalize the entire Korean Krunker community as a bunch of 12-year-olds playing a meme game. We (or at least I) didn't want that, so when I first spearheaded the Korean translation back in October, I tried to keep it as formal as I could without sacrificing the readability and friendliness.

**Comment by tr0922** [comment]
> Well, it wouldn't be a problem if the prior translations had already been in a more casual tone, but that's not the case here. I would actually argue that having translations in such a casual voice would unintentionally generalize the entire Korean Krunker community as a bunch of 12-year-olds playing a meme game (which undoubtedly does make up the majority of the playerbase, but still). We (or at least I) didn't want that, so when I first spearheaded the Korean translation back in October 2020, I tried to keep it as formal as I could without sacrificing the readability and friendliness.
> 
> But I do understand where you're coming from; I'll keep your points in mind when I translate in the future.
> 
> Edit: Grammar.

**Comment by tr0922** [comment]
@apinklover thanks :D
I'll try to be formal as possible when it's rly necessary!
but....does that mean my translation's not working out or smth? I'm sorry if that's the truth :/

**Comment by mty22** [comment]
Use the existing translation as a base line for written formalities. Since @tr0922 submitted the first pull request for the most recent update, it makes sense to work with him/her on this resulting in a overall positive result for all players who use Korean language within Krunker. :)

It also up-skills everyone participating in the translation project.

**Comment by tr0922** [comment]
Thanks! I'll try and edit it as best as I can!

**Comment by tr0922** [comment]
@mty22 @YuniQ152 @apinklover Did some changes, check it out and see if anything is missing or not rly good :D

**Comment by apinklover** [comment]
I think it's best to minimize the use of loanwords from English. I do understand you're trying to make the text more legible, but if too much random English is tossed around in what's supposed to be Korean, it might be off-putting for people who actually read the text.

**Comment by tr0922** [comment]
@apinklover k I'll edit it again :D thanks for the tip!

**Comment by tr0922** [comment]
@mty22 @apinklover @YuniQ152 Edited it again, this time a little bit :/ check it out :D

**Comment by apinklover** [comment]
There's a lot more to work on. There are missing translations, and as @dojinshi and I have mentioned, please stick to the original formality of the existing translations.

**Comment by tr0922** [comment]
@apinklover OK! Time to get to work :/ so, I guess I need these ;
1.Proper formality.
2.Missing Translations (tho I don't get it I thought we translated everything?)
Well, if we have to talk more, we can talk freely in Discord. Send a DM to tr0922#3835 if any problems occur with me.
Thanks!

**Comment by mty22** [comment]
@tr0922 great - thank you for the response. I'll just decline this pull request until some more updates are complete. :) re-open when ready.

Cheers.

**Comment by tr0922** [comment]
@mty22 will do. Thanks! I'll go to work right away!

**Pull request closed without merging**
