### PR TITLE
Update zh.js (v4.2.2)

### PR DESCRIPTION
**Pull request by 0v0katai**
Updated to v4.2.2 + Fixed some other errors
(开镜 means to use the scope to aim, while 瞄准 means to aim. In this case since knife can be aimed without scope, 瞄准 is more appropriate)

### CODE REVIEW

**Comment by 0v0katai** [comment]
Ignore the commits 5723818 and 9259df4 as they were created accidentially on my GitHub Desktop.

**Review by Awesome-Boy-001 — COMMENTED** [review]
Looks good! But here're some suggestions I made:

92 settings.network.netRate 网络刷新率 (Hz)
294 settings.gameprivacy.partner 显示游戏合作徽章
330 settings.audio.input 音量/麦克风输入
331 settings.audio.mic 麦克风音量
361 settings.viewmodel.toggleADS 切换瞄准镜

**Comment by 0v0katai** [comment]
(WIP)

> 92 settings.network.netRate 网络刷新率 (Hz)

Good one.

> 294 settings.gameprivacy.partner 显示游戏合作徽章

Maybe 显示游戏合作伙伴徽章 is more clear.

> 330 settings.audio.input 音量/麦克风输入

I translated it to 输入设备 which means "Input Device" as this setting just choose the input device. 音频和麦克风输入

> 331 settings.audio.mic 麦克风音量


> 361 settings.viewmodel.toggleADS 切换瞄准镜

The meaning and function of this setting are the same with "settings.viewmodel.toggleAim" which seems to be deprecated in Krunker, and 切换瞄准 is a common term to describe the meaning of "toggle/click to aim instead of hold to aim".

**Review by Awesome-Boy-001 — COMMENTED** [review]
Looks better now! Words and sentences are specific and accurate.

**Review by Awesome-Boy-001 — COMMENTED** [review]
Looks good and seems like some are simplified.

**Review by Awesome-Boy-001 — COMMENTED** [review]
Looks good. Here're two suggestions I made:

710 server.config.private 私服器
828 windows.playerlist.flag 您确定要标记 {0} 为黑客吗？

**Comment by 0v0katai** [comment]
> Looks good. Here're two suggestions I made:
> 
> 710 server.config.private 私服器
> 828 windows.playerlist.flag 您确定要标记 {0} 为黑客吗？

For line 710, "私服" is a common abbreviation of "私人服務器".
For line 828, "标记" implies the meaning of "tagging" too.

**Comment by mty22** [comment]
kr queued

**Pull request merged**
