### PR TITLE
Rebuild hu.js (Hungarian) based on en.js (v3.8.1)

### PR DESCRIPTION
**Pull request by Kmiki07**
I would like to ask CalmDestroyer#2400 for the review.
(ps.: I might have created this request already, github was bugging a bit so I'm not sure about it)

### CODE REVIEW

**Comment by mty22** [comment]
Looks good, than you. Will wait on Clam to review. :)

**Comment by calmdestroyer** [comment]
Sorry that I took so long with the review. I was really busy and I didn't want to rush it, so I waited untill I have a lot of free time so I can do my best. I created a document on everything that needs to be changed in the translation. I will attach the file here. 
[hungarian review.docx](https://github.com/mty22/krunker.io-translations/files/6359880/hungarian.review.docx)
The rest of the translation is fine. If you change everything from the document it is good to go in my opinion.

**Comment by mty22** [comment]
@calmdestroyer are you able to paste that as a text file instead?

**Comment by mty22** [comment]
I'll merge this one in and add it to the `work-in-progress` folder.

**Comment by calmdestroyer** [comment]
[review.txt](https://github.com/mty22/krunker.io-translations/files/6415013/review.txt)

**Pull request merged**
