### PR TITLE
Updates in es.js

### PR DESCRIPTION
**Pull request by johnaccardi**
Changes:
- Accents
- English words to spanish

### CODE REVIEW

**Comment by johnaccardi** [comment]
@mty22 Any chance you can review this if is possible please or tell one of the members in the Spanish Contributors team please.

**Review by 1opez — APPROVED** [review]

**Comment by mty22** [comment]
```
# [Spanish](https://github.com/mty22/krunker.io-translations/blob/main/es.js) (Español)
* [nightz](https://krunker.io/social.html?p=profile&q=xlNightmare) (nightz#6678)
* [MGVoltJesk](https://krunker.io/social.html?p=profile&q=MGVoltJesk) (MGVoltJesk#8000)
* [cesar](https://krunker.io/social.html?p=profile&q=AMOLAPIJA) (cesar#9999)
* [Aby3](https://krunker.io/social.html?p=profile&q=Aby3) (Aby3#7380)
* [Sonicglass](https://krunker.io/social.html?p=profile&q=Sonicglass) (Sonicglass#1532)
```

@johnaccardi feel free to pick someone from the list above. I've also pinged Aby3 in Krunker Bunker.

Also, can you please let us know your IGN?

**Review by Aby3kr — CHANGES_REQUESTED** [review]
Minor mistakes in es.js #440 

Line 64: use "Está en racha de" instead of "Es de" and delete "Racha"
Line 155: use "Cuando" instead of "Cuandó"

Revert every single "qué" changed in this update to "que" . They are all wrong

**Comment by johnaccardi** [comment]
Thanks @Aby3kr for the review and suggesting this changes.

**Comment by johnaccardi** [comment]
Thanks! for viewing the update and checking the pull-request, my IGN is johnaccardi and I don't really mind which Spanish translator, any of them would be ok.

**Comment by mty22** [comment]
kr queued

**Pull request merged**
