### PR TITLE
Updated fr.js | 100% complete

### PR DESCRIPTION
**Pull request by enygmate**
New translations and corrected old ones

### CODE REVIEW

**Review by Sayrix — APPROVED** [review]
Traduction correcte.

**Review by R3dlessX — APPROVED** [review]

**Review by Christian-Martins — APPROVED** [review]
👍

**Review by enygmate — COMMENTED** [review]
enygmate | Enygmate#2222

**Review by H2o8685 — APPROVED** [review]

**Comment by mty22** [comment]
ty ty

**Review by mty22 — APPROVED** [review]
Honestly, this is the kind of quality I love to see.

Thank you to everyone involved.

**Comment by enygmate** [comment]
> Honestly, this is the kind of quality I love to see.
> 
> Thank you to everyone involved.

Glad to help ☻

**Pull request merged**
