### PR TITLE
Update pr.js

### PR DESCRIPTION
**Pull request by Frediy99**
Made by me: Frediy99
In Game Nick: zalfredomz

### CODE REVIEW

**Comment by mty22** [comment]
Thank you! I'll try to find a reviewer once I have a bit of time.

**Comment by Frediy99** [comment]
> Thank you! I'll try to find a reviewer once I have a bit of time.

**Comment by mty22** [comment]
@Frediy99 any reason why you closed this pull request?

**Comment by Frediy99** [comment]
> @Frediy99 any reason why you closed this pull request?

Was a miss click sry, i thinked close with commente only delete my comment, but this close the pull request, was a wrong, but i re-open

**Comment by mty22** [comment]
user submitted second pull request: https://github.com/mty22/krunker.io-translations/pull/142

^ work from there

**Pull request closed without merging**
